import localFont from "next/font/local";
import "./globals.css";
import CustomerLayout from "@/components/layouts/customer-layout";



const geistSans = localFont({
  src: "../../public/assets/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../public/assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "DreamWheels",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"></link>
      </head>
      
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CustomerLayout>
        {children}
        </CustomerLayout>

      </body>
    </html>
  );
}
